config/routes.rb
WorshipTogether::Application.routes.draw do
  root 'users#index'

  resources :users
  resources :rides
  resources :churches, shallow: true do
    resources :services
  end

  get 'login', to: 'logins#new', as: :login
  post 'login', to: 'logins#create', as: :logins
  delete 'logout', to: 'logins#destroy', as: :logout

  

end

app/models/church.rb
class Church < ActiveRecord::Base
  belongs_to :user, inverse_of: :church_managed
  has_many :services, inverse_of: :church
  has_many :users, inverse_of: :church

  accepts_nested_attributes_for :services
end

app/models/locking_example.rb
class LockingExample < ActiveRecord::Base
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  has_many :user_rides
  has_many :users, through: :user_rides
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :church, inverse_of: :services
  has_many :rides

  validates :church, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :rides_provided, class_name: 'Ride', foreign_key: 'user_id'
    has_many :user_rides
    has_many :rides, through: :user_rides

    belongs_to :church, inverse_of: :users
    has_one :church_managed, inverse_of: :user, class_name: 'Church', foreign_key: 'user_id'

    has_secure_password

    validates :name, presence: true
    validates :email,
	presence: true,
	format: { with: /\A         # begin of input
			 [-\w+.]+   # dash, wordy, plus, or dot characters
			 @          # required at sign
			 [-a-z\d.]+ # dash, letter, digit, or dot chars
			 \z         # end of input
		        /xi }
    validates :password, presence: true
end

app/models/user_ride.rb
class UserRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include LoginsHelper
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
    def new
	@church = Church.new
	@church.services.build
    end

    def create
	@church = Church.new(church_params)
	@church.user = current_user
	if @church.save
	    flash[:success] = "Church created"
	    redirect_to @church
	else
	    flash.now[:danger] = "Unable to create church"
	    render 'new'
	end
    end

    private

    def church_params
	params.require(:church).permit(:name,
				       :web_site,
				       :description,
				       :picture,
				       services_attributes: [ :start_time,
							      :finish_time,
							      :location ] )
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def new
    end

    def create
	user = User.find_by(name: params[:username])
	if user && user.authenticate(params[:password])
	    flash[:success] = 'Logged in'
	    session[:user_id] = user.id
	    redirect_to users_path
	else
	    flash.now[:danger] = 'Invalid username or password'
	    render 'new'
	end
    end

    def destroy
	flash[:info] = 'Logged out'
	session[:user_id] = nil
	redirect_to users_path
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
    def index
	order_param = (params[:order] || :Date).to_sym
	ordering = case order_param
		   when :Date
		       :date
		   when :Service
		       :service_id
		   end
	@rides = Ride.order(ordering)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :ensure_user_logged_in, only: [:edit, :update, :destroy]
    before_action :ensure_correct_user, only: [:edit]
    before_action :ensure_admin, only: [:destroy]

    def index
	@users = User.all
    end

    def new
	@user = User.new
    end

    def create
	@user = User.new(user_params)
	if @user.save
	    flash[:success] = "Welcome to the site, #{@user.name}"
	    redirect_to @user
	else
	    flash.now[:danger] = "Unable to create new user"
	    render 'new'
	end
    end

    def show
	@user = User.find(params[:id])
    rescue
	flash[:danger] = "Unable to find user"
	redirect_to users_path
    end

    def edit
    end

    private

    def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def ensure_user_logged_in
	unless current_user
	    flash[:warning] = 'Not logged in'
	    redirect_to login_path
	end
    end

    def ensure_correct_user
	@user = User.find(params[:id])
	unless current_user?(@user)
	    flash[:danger] = "Cannot edit other user's profiles"
	    redirect_to root_path
	end
    rescue
	flash[:danger] = "Unable to find user"
	redirect_to users_path
    end

    def ensure_admin
	unless current_user.admin?
	    flash[:danger] = 'Only admins allowed to delete users'
	    redirect_to root_path
	end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
    def current_user
	User.find(session[:user_id]) if session[:user_id]
    end

    def current_user?(user)
	current_user == user
    end

    def logged_in?
	session[:user_id]
    end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/churches/_fields.html.erb
<%= f.label :name, 'Church Name' %>
<%= f.text_field :name %>

<%= f.label :web_site %>
<%= f.text_field :web_site %>

<%= f.label :picture %>
<%= f.text_field :picture %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.fields_for :services do |builder| %>
    <%= builder.label :start_time %>
    <%= builder.text_field :start_time %>

    <%= builder.label :finish_time %>
    <%= builder.text_field :finish_time %>

    <%= builder.label :location %>
    <%= builder.text_field :location %>
<% end %>

app/views/churches/new.html.erb
<%= render 'shared/errors', object: @church %>

<%= form_for @church do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>

    <%= form.submit 'Create new church' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorshipTogether</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
    <ul>
	<% if logged_in? %>
	    <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
	<% else %>
	    <li><%= link_to 'Log In', login_path %></li>
	<% end %>
    </ul>
</nav>

<% flash.each do |type, message| %>
    <p class="alert alert-<%= type %>"><%= message %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>Sign In</h1>

<%= form_tag logins_path do %>
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:username] %>

    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password] %>

    <%= submit_tag 'Log In' %>
<% end %>

app/views/rides/_ride.html.erb
<li>
    <ul>
	<li>From: <%= link_to ride.user.name, ride.user %></li>
	<li>To: <%= ride.service.church.name %></li>
	<li>Service: <%= ride.service.location %> @ <%= ride.service.start_time %></li>
	<li>Date: <%= ride.date %>
	<li><%= link_to 'Ride details', ride %></li>
    </ul>
</li>

app/views/rides/index.html.erb
<h1>List of rides</h1>

<p><%= pluralize(@rides.count, 'ride') %></p>
<ol><%= render @rides %></ol>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <p class="ALERT-danger">The form has <%= pluralize(object.errors.count, 'error') %>.</p>
    <ul>
	<% object.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	<% end %>
    </ul>
<% end %>

app/views/users/_fields.html.erb
<%= f.label :name, 'Username' %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, 'Confirmation' %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
    <%= user.name %>: <%= user.email %>
    <%= link_to 'delete', user, method: :delete %>
</li>

app/views/users/edit.html.erb
<h1>Edit profile</h1>
<%= render 'shared/errors', object: @user %>

app/views/users/index.html.erb
<h1>List of users</h1>

<p><%= pluralize(@users.count, 'user') %></p>
<ol><%= render @users %></ol>

app/views/users/new.html.erb
<%= render 'shared/errors', object: @user %>

<%= form_for @user do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>

    <%= form.submit 'Submit' %>
<% end %>

app/views/users/show.html.erb
<h1>Profile Page for <%= @user.name %></h1>

<p>Email: <%= @user.email %></p>